#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'plusMinus' function below.
#
# The function accepts INTEGER_ARRAY arr as parameter.
#

def plusMinus(arr):
    # Write your code here
    pos=0
    neg=0
    nul=0
    for each in arr:
        if each>0:
            pos=pos+1
        elif each<0:
            neg=neg+1
        elif each==0:
            nul=nul+1
    print(round(pos/len(arr),6))
    print(round(neg/len(arr),6))
    print(round(nul/len(arr),6))

if __name__ == '__main__':
    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    plusMinus(arr)
